### PR TITLE
pull again

### PR DESCRIPTION
**Pull request by RonnyWu**
Forgive me for not having VS. Use sublime to modify these.
Some grammatical mistakes may require your help.

about [KSP.Localization](https://kerbalspaceprogram.com/api/class_k_s_p_1_1_localization_1_1_localizer.html)

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
This won't work, besides having syntax errors, you can't have a non-static default, see the message below:


Error	CS0120	An object reference is required for the non-static field, method, or property 'ConfirmDialog.locStringOk'	Toolbar	D:\Users\jbb\github\ksp_toolbar\Toolbar\Internal\GUI\ConfirmDialog.cs	47	Active

And I already fixed it as follows:

internal ConfirmDialog(string title, string text, Action onOk, Action onCancel, string okText = "OK", string cancelText = "Cancel") : base()
        {
            if (okText == "OK")
                okText = Localizer.Format("#TOOLBAR_UI_OK");
            if (cancelText == "Cancel")
                cancelText = Localizer.Format("#TOOLBAR_UI_CANCEL");

**Comment by linuxgurugamer** [comment]
Look at the new branch "localization" which has all of your changes and my fixes

**Comment by RonnyWu** [comment]
thanks !

https://github.com/linuxgurugamer/ksp_toolbar/releases/tag/1.7.16.0
has some problems.
image

Can you give me a try?

**Comment by RonnyWu** [comment]
I need a latest link

**Pull request closed without merging**
