### PR TITLE
Add a german translation

### PR DESCRIPTION
**Pull request by mwerle**
Not exactly a core supported language, but here's a candidate for the german translation.

### CODE REVIEW

**Comment by RonnyWu** [comment]
Oh, sorry, I modified the translation and added a new item.

````
#TOOLBAR_UI_CONFIGURE_VISIBLE_BUTTONS_HINT = Configure Visible Toolbar Buttons
````

**Comment by RonnyWu** [comment]
I think let @linuxgurugamer  add it, then @mwerle  will be better translated.

**Comment by linuxgurugamer** [comment]
Please add a line for the following:

TOOLBAR_UI_CONFIGURE_VISIBLE_BUTTONS_HINT

This was just added to the others, so you had no way to do it until now.

Thanks

**Comment by linuxgurugamer** [comment]
Thank you!!!

**Pull request merged**
