### PR TITLE
Correct translation file

### PR DESCRIPTION
**Pull request by RonnyWu**
Remove extra strings ( " ) and Record.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
We seem to have crossed.  I moved the dictionary into the GameData/000_Toolbar directory, could you please redo this.

There are conflicting files in the pull so I can't merge it

**Comment by linuxgurugamer** [comment]
Also, when you do this, could you please split each language into it's own file?
Thanks

**Comment by linuxgurugamer** [comment]
If you can't, let me know, and I'll do it manually

**Comment by RonnyWu** [comment]
Now it is my hometown at night, you do it. The translation of the test changes, I will submit. I found some translation problems, but I have to go to bed.

**Comment by linuxgurugamer** [comment]
working on it now, please take a look in the morning

**Comment by RonnyWu** [comment]
Good morning ~ emmmm, maybe it's good night to say ....

**Pull request closed without merging**
